name: Release

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    runs-on: "ubuntu-latest"
    needs: [lint, scan, test]

    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          tag_prefix: v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
